name: Quick-CI

# An efficient fast CI
# - Only depends on tools already available in the available image.
# - Early outs on lint failures
# - Runs very liberally 
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04 
    steps:
    - uses: actions/checkout@v2
      
    - name: Check clang-format
      run: |
        pwd
        ls -la
        find . -regex '.*\.\(cpp\|h\)'  -exec clang-format-12 -style=file -i -n -Werror {} +

  build:
    runs-on: ubuntu-20.04 
    env:
      CC: clang-12
      CXX: clang++-12

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest
      
